[피드백 업로드 완료]
growth-up/java-study-project pull request #8
Opened 2021-04-18 17:17 UTC by hwihwi99

20210418.md에 피드백 업로드 완료하였습니다.

2021-04-19 09:59 UTC, aeomhs requested changes
정리 정말 감사합니다!! 👍👍👍
아래 `test.txt` 파일만 지워주세요! 😎

2021-04-19 09:59 UTC, aeomhs commented on test.txt
> +test test
요 파일은 지워주세요 ! 🙏

2021-04-19 09:59 UTC, aeomhs commented on note/20210418.md
> +- 빈 생성자를 만드는 것은 습관적으로 하기, 여러가지 생성자 생성 가능(오버로딩 개념으로)
약간의 오해 소지가 있을 수 있는 내용 의견 달아 두겠습니다!

음... 항상 빈 생성자를 만들어야하는 것은 아니구요!
생성자를 따로 선언하지 않으면, 자동으로(암묵적으로) 빈 생성자가 만들어지는데,
이런 방식으로 빈 생성자를 사용할 경우 이후에 문제가 발생할 수 있습니다!
> 특히 리플렉션이라는 방식을 통해 동적으로 무언가를 하다보면 많이 발생할 수 있습니다..!
결론은, 만약 빈 생성자를 사용한다면(필요하다면) 명시적으로 작성하자! 입니다.

스터디 당시에 리플렉션 이야기까지하면 너무 장황해질 것 같아서 생략했는데요,
넵 ㅋㅋㅋ 그렇습니다...

2021-04-21 11:11 UTC, hwihwi99 commented
피드백 받기 완료.

2021-04-21 11:31 UTC, aeomhs approved these changes

2021-04-21 11:32 UTC, aeomhs commented
확인이 늦었네요! 
잘해주셨습니다 :) 
머지해주세요~

2021-04-21 13:38 UTC, hwihwi99 commented
마스터 브랜치에서 git merge hwi-feedback 이라고 하니깐 14줄 삽입 1줄 삭제 등등의 말이 나오면서 성공적으로 끝난 것 같기는 한데 master에 병합이 안된 것 같아서요..혹시 다른 명령어를 사용해야 하나요..??ㅠㅠ

2021-04-21 13:53 UTC, hwihwi99 commented
아 아닙니당! 해결했습니다! 맞게 한건지 한번만 확인 부탁드려요ㅎㅎ

2021-04-22 13:47 UTC, aeomhs commented
방금 제가 20210418 노트를 수정해서 충돌이 발생했네요, 
이 경우 충돌을  꼭 resolve 해주셔야 합니다.
방법은 2가지가 있는데요,
로컬에서 하는 방법과
리모트(GitHub Web)에서 하는 방법이 있습니다.
로컬에서 하는 방법은 다음과 같습니다.
1. 우선 작업중인 브랜치로 체크아웃을 합니다.
2. 최신으로 받아온 master 브랜치와 병합을 수행합니다. (`master -> 작업중인 브랜치`)
3. conflicts 를 resolve 합니다.
4. 이런식으로 내가 작업중인 브랜치에서 유지하고 싶은 내용과, merge 하고 싶은 브랜치에서 유지하고 싶은 내용 등을 적절하게 선별하는 작업입니다.
5. 이렇게 수행한 뒤에 remote 서버로 다시 push를 수행하게되면 됩니다. 

웹에서 하는 방법은 다음과 같습니다.

2021-04-26 15:06 UTC, merged

2021-04-26 15:11 UTC, aeomhs commented
아주 잘하셨습니다!!!! 👏👏👏
첫번째 머지를 하셨네요!🎉🎉